site_name: Chatkit Python SDK
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - navigation.path
    - navigation.sections
    - content.code.annotate
  palette:
    primary: black
  logo: assets/logo.svg
  favicon: images/favicon-platform.svg

repo_name: chatkit-python
repo_url: https://github.com/openai/chatkit-python

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          selection:
            docstring_style: google
          options:
            signature_crossrefs: true
            members_order: source
            separate_signature: true
            show_signature_annotations: true
            heading_level: 3
            inherited_members: false
            filters:
              - "!^_"
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py

nav:
  - Home: index.md
  - Quick start: quickstart.md
  - Concepts:
      - Threads and items: concepts/threads.md
      - Thread stream events: concepts/thread-stream-events.md
      - Widgets: concepts/widgets.md
      - Actions: concepts/actions.md
      - Entities: concepts/entities.md
  - Guides:
      - Respond to a user message: guides/respond-to-user-message.md
      - Let users browse past threads: guides/browse-past-threads.md
      - Accept attachments: guides/accept-attachments.md
      - Make client tool calls: guides/make-client-tool-calls.md
      - Send client effects: guides/send-client-effects.md
      - Show progress for long-running tools: guides/show-progress-for-long-running-tools.md
      - Stream widgets: guides/stream-widgets.md
      - Handle widget actions: guides/handle-widget-actions.md
      - Create custom forms: guides/create-custom-forms.md
      - Handle feedback: guides/handle-feedback.md
      - Allow @-mentions in user messages: guides/allow-mentions.md
      - Add annotations in assistant messages: guides/add-annotations.md
  - API Reference:
      - Overview: api/chatkit/index.md
      - Modules:
          - actions: api/chatkit/actions.md
          - agents: api/chatkit/agents.md
          - errors: api/chatkit/errors.md
          - server: api/chatkit/server.md
          - store: api/chatkit/store.md
          - types: api/chatkit/types.md
          - widgets: api/chatkit/widgets.md
  - Release process / changelog: release.md
  - ChatKit JS Docs: https://openai.github.io/chatkit-js/
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

watch:
  - chatkit
