site_name: Chatkit Python SDK
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - navigation.sections
    - navigation.path
    - navigation.expand
    - content.code.annotate
  palette:
    primary: black
  logo: assets/logo.svg
  favicon: images/favicon-platform.svg

repo_name: chatkit-python
repo_url: https://github.com/openai/chatkit-python

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          selection:
            docstring_style: google
          options:
            signature_crossrefs: true
            members_order: source
            separate_signature: true
            show_signature_annotations: true
            heading_level: 3
            inherited_members: false
            filters:
              - "!^_"
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py

nav:
  - Home: index.md
  - Guides:
      - Serve ChatKit from your backend: guides/serve-chatkit.md
      - Persist ChatKit threads and messages: guides/persist-chatkit-data.md
      - Convert user input to model input: guides/convert-user-input.md
      - Run inference: guides/run-inference.md
      - Stream responses back to your user: guides/stream-thread-events.md
      - Add features:
          - Save thread titles: guides/add-features/save-thread-titles.md
          - Accept attachments: guides/add-features/accept-attachments.md
          - Make client tool calls: guides/add-features/make-client-tool-calls.md
          - Send client effects: guides/add-features/send-client-effects.md
          - Show progress for long-running tools: guides/add-features/show-progress-for-long-running-tools.md
          - Stream widgets: guides/add-features/stream-widgets.md
          - Handle widget actions: guides/add-features/handle-widget-actions.md
          - Create custom forms: guides/add-features/create-custom-forms.md
          - Handle feedback: guides/add-features/handle-feedback.md
          - Allow @-mentions in user messages: guides/add-features/allow-mentions.md
          - Disable new messages for a thread: guides/add-features/disable-new-messages.md
          # - Add annotations in assistant messages
  - API Reference:
      - Overview: api/chatkit/index.md
      - Modules:
          - actions: api/chatkit/actions.md
          - agents: api/chatkit/agents.md
          - errors: api/chatkit/errors.md
          - server: api/chatkit/server.md
          - store: api/chatkit/store.md
          - types: api/chatkit/types.md
          - widgets: api/chatkit/widgets.md
  - Release process / changelog: release.md
  - ChatKit JS Docs: https://openai.github.io/chatkit-js/
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

watch:
  - chatkit
